version: '3'
services:
  proximity:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}
      TEMPLATE_NAME: ${TEMPLATE_NAME:-}
    image: proximity:latest
    volumes:
      - ../cards.txt:/app/cardslist   # Volume 1 - Mounts the default 'cards.txt' as cardslist
      - ../templates:/app/templates   # Volume 2 - Mounts templates from run/templates (i.e. normal and classic)
      - ../images:/app/images         # Volume 3 - Mounts the output folder
      - ../art:/app/art               # Volume 4 - Mounts local art folder
    command: --cards=cardslist --template=$TEMPLATE_NAME --use_official_art=true
